site_name: Kinesis Advantage Tidbits
site_url: https://ka.danieldk.eu/
repo_url: https://github.com/danieldk/kinesis-advantage/
nav:
  - Home: index.md
  - Advantage2: advantage2.md
  - Advantage360: advantage360.md
theme: readthedocs
markdown_extensions:
  - attr_list
